// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfakbcbogixcktvsvgwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmYWtiY2JvZ2l4Y2t0dnN2Z3dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MjE1NTgsImV4cCI6MjA2MTA5NzU1OH0.hKP7msEE2hY58eH7g3GUQg0DbsvfhNfC-zRBljnBL9A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);